/*
 * File: app/store/cidade.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('softruck.store.cidade', {
    extend: 'Ext.data.Store',

    requires: [
        'softruck.model.cidade',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'cidade',
            model: 'softruck.model.cidade',
            proxy: {
                type: 'jsonp',
                url: 'http://muvox.com.br/cidade.php',
                reader: {
                    type: 'json',
                    rootProperty: 'record.results'
                }
            }
        }, cfg)]);
    }
});