/*
 * File: app/store/mapa.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('softruck.store.mapa', {
    extend: 'Ext.data.Store',

    requires: [
        'softruck.model.mapa',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'mapa',
            model: 'softruck.model.mapa',
            proxy: {
                type: 'jsonp',
                limitParam: 'limitX',
                url: 'https://api.foursquare.com/v2/venues/search?client_id=40JVBWNP40V0BRDSFGOP1HCZGEI33DLGMHIAP0VHI2D3N2XD&client_secret=2SXCW1FXGQZUHFAJYG53CLOSNZTAXWFTZ5GVLH2B1A0NCWU3&v=20160526',
                reader: {
                    type: 'json',
                    rootProperty: 'response.venues'
                }
            }
        }, cfg)]);
    }
});