/*
 * File: app/view/panelMainViewModel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('softruck.view.panelMainViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.panelmain',

    requires: [
        'Ext.app.bind.Formula'
    ],

    formulas: {
        lbRaio: function(get) {
            var x = get('distancia');

            x = x/1000;
            return 'Dentro de '+x+' km';
        }
    }

});